
# =============================================================================
# S4 Class Definition
# =============================================================================

#' GTFParquet class
#' @import methods
#' @import GenomicRanges
#' @import GenomeInfoDb
#' @import GenomicFeatures
#' @import S4Vectors
#' @import IRanges
#' @importFrom arrow read_parquet open_dataset
#' @importFrom dplyr select filter collect arrange any_of pull distinct
#' @description
#' An S4 class for accessing GTF annotations stored in Parquet format.
#' Unlike TxDb, preserves all GTF attributes (gene_type, gene_name, 
#' transcript_support_level, tags, etc.)
#'
#' @details
#' GTFParquet objects are created by the \code{\link{GTFParquet}} constructor
#' function from a directory of Parquet files generated by \code{gtf_to_parquet.py}.
#' 
#' The class implements methods for GenomicFeatures generics including
#' \code{\link[GenomicFeatures]{genes}}, \code{\link[GenomicFeatures]{transcripts}},
#' \code{\link[GenomicFeatures]{exons}}, \code{\link[GenomicFeatures]{cds}},
#' \code{\link[GenomicFeatures]{exonsBy}}, \code{\link[GenomicFeatures]{cdsBy}},
#' and \code{\link[GenomicFeatures]{transcriptsBy}}.
#'
#' All methods support a \code{filter} argument for efficient querying
#' (e.g., \code{filter = list(gene_type = "protein_coding")}).
#'
#' @slot path Character. Path to the Parquet directory.
#' @slot files List. Paths to individual Parquet files.
#' @slot available Logical vector. Which files are present.
#' @slot is_partitioned Logical. Whether genes are partitioned by chromosome.
#' @slot .genome Character. Reference genome build (e.g., "GRCh38").
#'
#' @seealso
#' \itemize{
#'   \item \code{\link{GTFParquet}} for the constructor function
#'   \item \code{\link{genes,GTFParquet-method}} for extracting genes
#'   \item \code{\link{transcriptsBy,GTFParquet-method}} for grouped extractors
#'   \item \code{\link[GenomicFeatures]{TxDb}} for comparison with TxDb objects
#' }
#'
#' @examples
#' \dontrun{
#' # Create from Parquet directory
#' gtf <- GTFParquet(system.file("gc49", package="lkparq"))
#' 
#' # Extract genes with full attributes
#' gr <- genes(gtf)
#' mcols(gr)  # gene_name, gene_type, level, tags, etc.
#' 
#' # Filter by gene type
#' pc <- genes(gtf, filter = list(gene_type = "protein_coding"))
#' }
#'
#' @exportClass GTFParquet
setClass("GTFParquet",
  slots = c(
    path = "character",
    files = "list",
    available = "logical",
    is_partitioned = "logical",
    .genome = "character"
  )
)


#' Create a GTFParquet object
#'
#' @param path Path to directory containing Parquet files from gtf_to_parquet.py
#' @return A GTFParquet S4 object
#' @export
#' @examples
#' gtf <- GTFParquet(system.file("gc49", package="lkparq"))
#' genes(gtf)
#' genes(gtf, filter = list(gene_type = "protein_coding"))
GTFParquet <- function(path) {
  path <- normalizePath(path, mustWork = TRUE)
  
  # Check which files exist
  files <- list(
    genes = file.path(path, "genes.parquet"),
    transcripts = file.path(path, "transcripts.parquet"),
    exons = file.path(path, "exons.parquet"),
    cds = file.path(path, "cds.parquet"),
    features = file.path(path, "features.parquet"),
    metadata = file.path(path, "metadata.parquet")
  )
  
  available <- sapply(files, file.exists)
  
  # Check for partitioned genes directory
  is_partitioned <- dir.exists(file.path(path, "genes"))
  if (is_partitioned) {
    files$genes <- file.path(path, "genes")
    available["genes"] <- TRUE
  }
  
  # Load genome from metadata if available
  genome_val <- NA_character_
  if (available[["metadata"]]) {
    meta <- arrow::read_parquet(files$metadata)
    meta_list <- setNames(meta$value, meta$name)
    if ("genome" %in% names(meta_list)) {
      genome_val <- meta_list[["genome"]]
    }
  }
  
  new("GTFParquet",
      path = path,
      files = files,
      available = available,
      is_partitioned = is_partitioned,
      .genome = genome_val)
}


#' @export
setMethod("show", "GTFParquet", function(object) {
  cat("GTFParquet object\n")
  cat("  Path:", object@path, "\n")
  if (!is.na(object@.genome)) {
    cat("  Genome:", object@.genome, "\n")
  }
  cat("  Available tables:\n")
  for (name in names(object@available)) {
    status <- if (object@available[[name]]) "[x]" else "[ ]"
    cat(sprintf("    %s %s\n", status, name))
  }
  
  # Show metadata if available
  if (object@available[["metadata"]]) {
    meta <- arrow::read_parquet(object@files$metadata)
    cat("  Metadata:\n")
    for (i in seq_len(nrow(meta))) {
      cat(sprintf("    %s: %s\n", meta$name[i], meta$value[i]))
    }
  }
})


# =============================================================================
# GenomeInfoDb::genome method
# =============================================================================

#' @rdname GTFParquet-class
#' @export
setMethod("genome", "GTFParquet", function(x) {
  x@.genome
})


# =============================================================================
# GenomicFeatures::genes, transcripts, exons, cds methods
# =============================================================================

#' Extract genomic features from a GTFParquet object
#'
#' @name genes
#' @aliases genes,GTFParquet-method
#' @aliases transcripts,GTFParquet-method
#' @aliases exons,GTFParquet-method
#' @aliases cds,GTFParquet-method
#'
#' @description
#' Methods to extract genomic features from a GTFParquet object as GRanges.
#' Unlike TxDb methods, these preserve all GTF attributes as metadata columns.
#'
#' @usage
#' \S4method{genes}{GTFParquet}(x, columns=NULL, filter=NULL, use_versioned_ids=FALSE)
#'
#' \S4method{transcripts}{GTFParquet}(x, columns=NULL, filter=NULL, use_versioned_ids=FALSE)
#'
#' \S4method{exons}{GTFParquet}(x, columns=NULL, filter=NULL, use_versioned_ids=FALSE)
#'
#' \S4method{cds}{GTFParquet}(x, columns=NULL, filter=NULL)
#'
#' @param x A \code{\link{GTFParquet}} object.
#' @param columns Character vector of columns to include in \code{mcols}.
#'   If \code{NULL} (default), includes all available attribute columns.
#'   For genes: \code{gene_name}, \code{gene_type}, \code{source}, \code{level}, 
#'   \code{tags}, \code{havana_gene}.
#'   For transcripts: \code{transcript_name}, \code{transcript_type}, \code{gene_id},
#'   \code{gene_name}, \code{transcript_support_level}, \code{ccdsid}, \code{protein_id}.
#' @param filter Optional named list for filtering features.
#'   Names should be column names, values are vectors of acceptable values.
#'   Example: \code{filter = list(gene_type = "protein_coding", chrom = "chr1")}
#' @param use_versioned_ids Logical. If \code{TRUE}, use full versioned IDs
#'   (e.g., \code{ENSG00000141510.18}). If \code{FALSE} (default), use stripped IDs
#'   (e.g., \code{ENSG00000141510}).
#'
#' @details
#' These methods return \link[GenomicRanges]{GRanges} objects with feature IDs
#' as names and rich metadata columns from the original GTF file.
#'
#' The \code{filter} argument enables efficient server-side filtering through
#' Arrow/Parquet predicate pushdown, which can dramatically improve performance
#' compared to subsetting after loading.
#'
#' Available filter columns include:
#' \itemize{
#'   \item \code{chrom}: Chromosome name
#'   \item \code{gene_type}: Gene biotype (e.g., "protein_coding", "lncRNA")
#'   \item \code{transcript_type}: Transcript biotype
#'   \item \code{level}: Annotation confidence (1=verified, 2=manual, 3=automatic)
#'   \item \code{source}: Annotation source ("HAVANA", "ENSEMBL")
#' }
#'
#' @return
#' A \link[GenomicRanges]{GRanges} object with:
#' \itemize{
#'   \item Feature IDs as \code{names}
#'   \item Genomic coordinates (\code{seqnames}, \code{ranges}, \code{strand})
#'   \item Genome build in \code{seqinfo} (e.g., "GRCh38")
#'   \item Rich metadata in \code{mcols}
#' }
#'
#' @seealso
#' \itemize{
#'   \item \code{\link{GTFParquet-class}} for the class definition
#'   \item \code{\link{transcriptsBy,GTFParquet-method}} for grouped extraction
#'   \item \code{\link[GenomicFeatures]{genes}} for the generic
#' }
#'
#' @examples
#' \dontrun{
#' gtf <- GTFParquet(system.file("gc49", package="lkparq"))
#'
#' # Extract all genes with full attributes
#' gr <- genes(gtf)
#' mcols(gr)  # gene_name, gene_type, level, tags, source, havana_gene
#'
#' # Filter by gene type
#' pc <- genes(gtf, filter = list(gene_type = "protein_coding"))
#' lnc <- genes(gtf, filter = list(gene_type = "lncRNA"))
#'
#' # Combine filters
#' pc_chr1 <- genes(gtf, filter = list(gene_type = "protein_coding", chrom = "chr1"))
#'
#' # Select specific columns only
#' gr <- genes(gtf, columns = c("gene_name", "gene_type"))
#'
#' # Use versioned IDs
#' gr <- genes(gtf, use_versioned_ids = TRUE)
#' names(gr)[1]  # "ENSG00000141510.18"
#'
#' # Transcripts with support level
#' tx <- transcripts(gtf)
#' high_conf <- tx[mcols(tx)$transcript_support_level == "1"]
#'
#' # Exons
#' ex <- exons(gtf, filter = list(chrom = "chr1"))
#'
#' # CDS with protein IDs
#' cds_gr <- cds(gtf)
#' mcols(cds_gr)$protein_id
#' }
#'
#' @rdname genes
#' @export
setMethod("genes", "GTFParquet", function(x, columns = NULL, filter = NULL, 
                                           use_versioned_ids = FALSE) {
  if (!x@available[["genes"]]) {
    stop("genes.parquet not found in: ", x@path)
  }
  
  default_cols <- c("gene_name", "gene_type", "source", "level", "tags", "havana_gene")
  if (is.null(columns)) {
    columns <- default_cols
  }
  
  id_col <- if (use_versioned_ids) "gene_id" else "gene_id_stripped"
  required_cols <- c(id_col, "chrom", "start", "end", "strand")
  select_cols <- unique(c(required_cols, columns))
  
  if (!is.null(filter)) {
    select_cols <- unique(c(select_cols, names(filter)))
  }
  
  ds <- arrow::open_dataset(x@files$genes)
  query <- ds |> dplyr::select(dplyr::any_of(select_cols))
  
  if (!is.null(filter)) {
    for (col_name in names(filter)) {
      query <- query |> dplyr::filter(.data[[col_name]] %in% filter[[col_name]])
    }
  }
  
  df <- query |> dplyr::collect() |> dplyr::arrange(chrom, start)
  
  .df_to_granges_rich(df, id_col = id_col, mcol_cols = columns, genome = x@.genome)
})


# =============================================================================
# GenomicFeatures::transcripts method
# =============================================================================

#' @rdname genes
#' @export
setMethod("transcripts", "GTFParquet", function(x, columns = NULL, filter = NULL,
                                                 use_versioned_ids = FALSE) {
  if (!x@available[["transcripts"]]) {
    stop("transcripts.parquet not found in: ", x@path)
  }
  
  default_cols <- c("transcript_name", "transcript_type", "gene_id", "gene_name",
                    "source", "level", "tags", "transcript_support_level",
                    "havana_transcript", "ccdsid", "protein_id")
  if (is.null(columns)) {
    columns <- default_cols
  }
  
  id_col <- if (use_versioned_ids) "transcript_id" else "transcript_id_stripped"
  required_cols <- c(id_col, "chrom", "start", "end", "strand")
  select_cols <- unique(c(required_cols, columns))
  
  if (!is.null(filter)) {
    select_cols <- unique(c(select_cols, names(filter)))
  }
  
  df <- arrow::read_parquet(x@files$transcripts, col_select = dplyr::any_of(select_cols))
  
  if (!is.null(filter)) {
    for (col_name in names(filter)) {
      df <- df |> dplyr::filter(.data[[col_name]] %in% filter[[col_name]])
    }
  }
  
  df <- df |> dplyr::arrange(chrom, start)
  
  .df_to_granges_rich(df, id_col = id_col, mcol_cols = columns, genome = x@.genome)
})


# =============================================================================
# GenomicFeatures::exons method
# =============================================================================

#' @rdname genes
#' @export
setMethod("exons", "GTFParquet", function(x, columns = NULL, filter = NULL,
                                           use_versioned_ids = FALSE) {
  if (!x@available[["exons"]]) {
    stop("exons.parquet not found in: ", x@path)
  }
  
  default_cols <- c("exon_number", "transcript_id", "gene_id", "source", "level", "tags")
  if (is.null(columns)) {
    columns <- default_cols
  }
  
  id_col <- if (use_versioned_ids) "exon_id" else "exon_id_stripped"
  required_cols <- c(id_col, "chrom", "start", "end", "strand")
  select_cols <- unique(c(required_cols, columns))
  
  if (!is.null(filter)) {
    select_cols <- unique(c(select_cols, names(filter)))
  }
  
  df <- arrow::read_parquet(x@files$exons, col_select = dplyr::any_of(select_cols))
  
  if (!is.null(filter)) {
    for (col_name in names(filter)) {
      df <- df |> dplyr::filter(.data[[col_name]] %in% filter[[col_name]])
    }
  }
  
  df <- df |> dplyr::arrange(chrom, start)
  
  .df_to_granges_rich(df, id_col = id_col, mcol_cols = columns, genome = x@.genome)
})


# =============================================================================
# GenomicFeatures::cds method
# =============================================================================

#' @rdname genes
#' @export
setMethod("cds", "GTFParquet", function(x, columns = NULL, filter = NULL) {
  if (!x@available[["cds"]]) {
    stop("cds.parquet not found in: ", x@path)
  }
  
  default_cols <- c("transcript_id", "gene_id", "protein_id", "exon_number",
                    "frame", "source", "level", "tags")
  if (is.null(columns)) {
    columns <- default_cols
  }
  
  required_cols <- c("cds_id", "chrom", "start", "end", "strand")
  select_cols <- unique(c(required_cols, columns))
  
  if (!is.null(filter)) {
    select_cols <- unique(c(select_cols, names(filter)))
  }
  
  df <- arrow::read_parquet(x@files$cds, col_select = dplyr::any_of(select_cols))
  
  if (!is.null(filter)) {
    for (col_name in names(filter)) {
      df <- df |> dplyr::filter(.data[[col_name]] %in% filter[[col_name]])
    }
  }
  
  df <- df |> dplyr::arrange(chrom, start)
  
  .df_to_granges_rich(df, id_col = "cds_id", mcol_cols = columns, genome = x@.genome)
})


# =============================================================================
# GenomicFeatures::exonsBy, cdsBy, transcriptsBy methods
# =============================================================================

#' Extract and group genomic features from a GTFParquet object
#'
#' @name transcriptsBy
#' @aliases transcriptsBy,GTFParquet-method
#' @aliases exonsBy,GTFParquet-method
#' @aliases cdsBy,GTFParquet-method
#'
#' @description
#' Generic functions to extract genomic features of a given type
#' grouped based on another type of genomic feature.
#' These methods extend the GenomicFeatures generics for GTFParquet objects.
#'
#' @usage
#' \S4method{transcriptsBy}{GTFParquet}(x, by="gene", filter=NULL)
#'
#' \S4method{exonsBy}{GTFParquet}(x, by=c("tx", "gene"), filter=NULL)
#'
#' \S4method{cdsBy}{GTFParquet}(x, by=c("tx", "gene"), filter=NULL)
#'
#' @param x A \code{\link{GTFParquet}} object.
#' @param by One of \code{"gene"}, \code{"tx"} (transcript).
#'   Determines the grouping. For \code{transcriptsBy}, only \code{"gene"}
#'   is currently supported.
#' @param filter Optional named list for filtering features before grouping.
#'   Names should be column names (e.g., \code{gene_type}, \code{chrom}),
#'   values are vectors of acceptable values.
#'   Example: \code{filter = list(gene_type = "protein_coding", chrom = "chr1")}
#'
#' @details
#' These functions return a \link[GenomicRanges]{GRangesList} object
#' where the ranges within each of the elements are ordered according
#' to the following rule:
#'
#' When using \code{exonsBy} or \code{cdsBy} with \code{by = "tx"},
#' the returned exons or CDS are ordered by ascending exon number for each
#' transcript, that is, by their position in the transcript.
#' In all other cases, the ranges will be ordered by chromosome, strand,
#' start, and end values.
#'
#' Unlike TxDb methods, GTFParquet methods preserve rich metadata columns
#' including \code{transcript_name}, \code{transcript_type}, \code{exon_number},
#' \code{protein_id}, and \code{frame}.
#'
#' The \code{filter} argument allows efficient server-side filtering before
#' data is loaded into R, which can dramatically improve performance for
#' large annotation files.
#'
#' @return
#' A \link[GenomicRanges]{GRangesList} object. The names of the list elements
#' are the IDs of the grouping features (gene IDs or transcript IDs).
#'
#' For GTFParquet objects, the names use stripped (unversioned) IDs by default
#' (e.g., \code{ENSG00000141510} rather than \code{ENSG00000141510.18}).
#'
#' @seealso
#' \itemize{
#'   \item \code{\link{GTFParquet-class}} for the class definition
#'   \item \code{\link{genes,GTFParquet-method}} for extracting ungrouped features
#'   \item \code{\link[GenomicFeatures]{transcriptsBy}} for the generic
#'   \item \code{\link[GenomicFeatures]{exonsBy}} for the generic
#'   \item \code{\link[GenomicFeatures]{cdsBy}} for the generic
#' }
#'
#' @examples
#' \dontrun{
#' gtf <- GTFParquet(system.file("gc49", package="lkparq"))
#'
#' # Exons grouped by transcript (sorted by exon_number)
#' ebt <- exonsBy(gtf, by = "tx")
#' ebt[[1]]  # Exons for first transcript
#'
#' # Exons grouped by gene
#' ebg <- exonsBy(gtf, by = "gene")
#'
#' # CDS grouped by transcript
#' cbt <- cdsBy(gtf, by = "tx")
#'
#' # Transcripts grouped by gene
#' tbg <- transcriptsBy(gtf, by = "gene")
#'
#' # Filter to protein-coding only
#' pc_exons <- exonsBy(gtf, by = "tx", 
#'                     filter = list(gene_type = "protein_coding"))
#'
#' # Filter by chromosome
#' chr1_cds <- cdsBy(gtf, by = "tx", filter = list(chrom = "chr1"))
#' }
#'
#' @rdname transcriptsBy
#' @export
setMethod("exonsBy", "GTFParquet", function(x, by = c("tx", "gene"), filter = NULL) {
  by <- match.arg(by)
  
  if (!x@available[["exons"]]) {
    stop("exons.parquet not found")
  }
  
  group_col <- if (by == "tx") "transcript_id_stripped" else "gene_id_stripped"
  
  select_cols <- c("exon_id_stripped", "exon_number", "transcript_id_stripped",
                   "gene_id_stripped", "chrom", "start", "end", "strand")
  
  df <- arrow::read_parquet(x@files$exons, col_select = dplyr::any_of(select_cols))
  
  if (!is.null(filter)) {
    for (col_name in names(filter)) {
      df <- df |> dplyr::filter(.data[[col_name]] %in% filter[[col_name]])
    }
  }
  
  df <- df |> dplyr::arrange(.data[[group_col]], exon_number)
  
  .df_to_grangeslist(df, group_col = group_col, id_col = "exon_id_stripped",
                     mcol_cols = c("exon_number", "transcript_id_stripped", "gene_id_stripped"),
                     genome = x@.genome)
})


# =============================================================================
# GenomicFeatures::cdsBy method
# =============================================================================

#' @rdname transcriptsBy
#' @export
setMethod("cdsBy", "GTFParquet", function(x, by = c("tx", "gene"), filter = NULL) {
  by <- match.arg(by)
  
  if (!x@available[["cds"]]) {
    stop("cds.parquet not found")
  }
  
  group_col <- if (by == "tx") "transcript_id_stripped" else "gene_id_stripped"
  
  select_cols <- c("cds_id", "transcript_id_stripped", "gene_id_stripped",
                   "protein_id", "exon_number", "frame",
                   "chrom", "start", "end", "strand")
  
  df <- arrow::read_parquet(x@files$cds, col_select = dplyr::any_of(select_cols))
  
  if (!is.null(filter)) {
    for (col_name in names(filter)) {
      df <- df |> dplyr::filter(.data[[col_name]] %in% filter[[col_name]])
    }
  }
  
  df <- df |> dplyr::arrange(.data[[group_col]], exon_number)
  
  .df_to_grangeslist(df, group_col = group_col, id_col = "cds_id",
                     mcol_cols = c("protein_id", "exon_number", "frame",
                                   "transcript_id_stripped", "gene_id_stripped"),
                     genome = x@.genome)
})


# =============================================================================
# GenomicFeatures::transcriptsBy method
# =============================================================================

#' @rdname transcriptsBy
#' @export
setMethod("transcriptsBy", "GTFParquet", function(x, by = "gene", filter = NULL) {
  if (by != "gene") {
    stop("transcriptsBy currently only supports by='gene'")
  }
  
  if (!x@available[["transcripts"]]) {
    stop("transcripts.parquet not found")
  }
  
  select_cols <- c("transcript_id_stripped", "transcript_name", "transcript_type",
                   "gene_id_stripped", "chrom", "start", "end", "strand")
  
  df <- arrow::read_parquet(x@files$transcripts, col_select = dplyr::any_of(select_cols))
  
  if (!is.null(filter)) {
    for (col_name in names(filter)) {
      df <- df |> dplyr::filter(.data[[col_name]] %in% filter[[col_name]])
    }
  }
  
  df <- df |> dplyr::arrange(gene_id_stripped, start)
  
  .df_to_grangeslist(df, group_col = "gene_id_stripped", id_col = "transcript_id_stripped",
                     mcol_cols = c("transcript_name", "transcript_type"),
                     genome = x@.genome)
})


# =============================================================================
# GenomicFeatures::seqinfo method
# =============================================================================

#' Get sequence information from a GTFParquet object
#'
#' @param x A \code{\link{GTFParquet}} object.
#' @return A \link[GenomeInfoDb]{Seqinfo} object containing chromosome names
#'   and genome build.
#' @seealso \code{\link[GenomeInfoDb]{seqinfo}}
#' @rdname GTFParquet-class
#' @export
setMethod("seqinfo", "GTFParquet", function(x) {
  # Build seqinfo from genes table
  if (x@available[["genes"]]) {
    ds <- arrow::open_dataset(x@files$genes)
    chroms <- ds |>
      dplyr::select(chrom) |>
      dplyr::distinct() |>
      dplyr::collect() |>
      dplyr::pull(chrom) |>
      sort()
  } else if (x@available[["transcripts"]]) {
    df <- arrow::read_parquet(x@files$transcripts, col_select = "chrom")
    chroms <- sort(unique(df$chrom))
  } else {
    return(Seqinfo())
  }
  
  si <- Seqinfo(seqnames = chroms)
  if (!is.na(x@.genome)) {
    genome(si) <- x@.genome
  }
  si
})


# =============================================================================
# Feature Type Queries (custom generics)
# =============================================================================

#' Extract UTR and codon features from a GTFParquet object
#'
#' @name utrs
#' @aliases utrs,GTFParquet-method
#' @aliases codons,GTFParquet-method
#'
#' @description
#' Functions to extract UTR (untranslated region) and codon features
#' from a GTFParquet object. These features are stored in the features.parquet
#' file generated by gtf_to_parquet.py.
#'
#' @param x A \code{\link{GTFParquet}} object.
#' @param type For \code{utrs}: one of \code{"both"}, \code{"5prime"}, or \code{"3prime"}.
#'   For \code{codons}: one of \code{"both"}, \code{"start"}, or \code{"stop"}.
#' @param filter Optional named list for filtering features.
#'
#' @return A \link[GenomicRanges]{GRanges} object with metadata columns
#'   including \code{feature_type}, \code{transcript_id}, and \code{gene_id}.
#'
#' @examples
#' \dontrun{
#' gtf <- GTFParquet(system.file("gc49", package="lkparq"))
#' 
#' # 5' UTRs
#' utr5 <- utrs(gtf, type = "5prime")
#' 
#' # 3' UTRs
#' utr3 <- utrs(gtf, type = "3prime")
#' 
#' # Start codons
#' start <- codons(gtf, type = "start")
#' 
#' # Stop codons
#' stop <- codons(gtf, type = "stop")
#' }
#'
#' @rdname utrs
#' @export
setGeneric("utrs", function(x, type = "both", filter = NULL) standardGeneric("utrs"))

#' @rdname utrs
#' @export
setMethod("utrs", "GTFParquet", function(x, type = c("both", "5prime", "3prime"), 
                                          filter = NULL) {
  type <- match.arg(type)
  
  if (!x@available[["features"]]) {
    stop("features.parquet not found - no UTR data available")
  }
  
  df <- arrow::read_parquet(x@files$features)
  
  utr_types <- switch(type,
    "5prime" = c("five_prime_utr", "UTR"),
    "3prime" = c("three_prime_utr"),
    "both" = c("five_prime_utr", "three_prime_utr", "UTR")
  )
  
  df <- df |> dplyr::filter(feature_type %in% utr_types)
  
  if (!is.null(filter)) {
    for (col_name in names(filter)) {
      df <- df |> dplyr::filter(.data[[col_name]] %in% filter[[col_name]])
    }
  }
  
  if (nrow(df) == 0) {
    return(GRanges())
  }
  
  gr <- GRanges(
    seqnames = df$chrom,
    ranges = IRanges(start = df$start, end = df$end),
    strand = df$strand
  )
  
  mcols(gr) <- df[, c("feature_type", "transcript_id", "gene_id"), drop = FALSE]
  
  if (!is.na(x@.genome)) {
    si <- seqinfo(gr)
    genome(si) <- x@.genome
    seqinfo(gr) <- si
  }
  
  gr
})


#' @rdname utrs
#' @export
setGeneric("codons", function(x, type = "both", filter = NULL) standardGeneric("codons"))

#' @rdname utrs
#' @export
setMethod("codons", "GTFParquet", function(x, type = c("both", "start", "stop"),
                                            filter = NULL) {
  type <- match.arg(type)
  
  if (!x@available[["features"]]) {
    stop("features.parquet not found")
  }
  
  df <- arrow::read_parquet(x@files$features)
  
  codon_types <- switch(type,
    "start" = "start_codon",
    "stop" = "stop_codon",
    "both" = c("start_codon", "stop_codon")
  )
  
  df <- df |> dplyr::filter(feature_type %in% codon_types)
  
  if (!is.null(filter)) {
    for (col_name in names(filter)) {
      df <- df |> dplyr::filter(.data[[col_name]] %in% filter[[col_name]])
    }
  }
  
  if (nrow(df) == 0) {
    return(GRanges())
  }
  
  gr <- GRanges(
    seqnames = df$chrom,
    ranges = IRanges(start = df$start, end = df$end),
    strand = df$strand
  )
  
  mcols(gr) <- df[, c("feature_type", "transcript_id", "gene_id", "frame"), drop = FALSE]
  
  if (!is.na(x@.genome)) {
    si <- seqinfo(gr)
    genome(si) <- x@.genome
    seqinfo(gr) <- si
  }
  
  gr
})


# =============================================================================
# Convenience Functions
# =============================================================================

#' Convenience functions for common gene types
#'
#' @description
#' Helper functions to quickly extract genes of common biotypes.
#'
#' @param x A \code{\link{GTFParquet}} object.
#' @param ... Additional arguments passed to \code{\link{genes,GTFParquet-method}}.
#'
#' @return A \link[GenomicRanges]{GRanges} object.
#'
#' @examples
#' \dontrun{
#' gtf <- GTFParquet(system.file("gc49", package="lkparq"))
#' pc <- protein_coding_genes(gtf)
#' lnc <- lncRNA_genes(gtf)
#' }
#'
#' @name convenience-functions
#' @rdname convenience-functions
#' @export
protein_coding_genes <- function(x, ...) {
  genes(x, filter = list(gene_type = "protein_coding"), ...)
}


#' @rdname convenience-functions
#' @export
lncRNA_genes <- function(x, ...) {
  genes(x, filter = list(gene_type = "lncRNA"), ...)
}


#' List available gene or transcript types
#'
#' @description
#' Query the available biotypes in the annotation and their counts.
#'
#' @param x A \code{\link{GTFParquet}} object.
#'
#' @return A table of biotype counts.
#'
#' @examples
#' \dontrun{
#' gtf <- GTFParquet(system.file("gc49", package="lkparq"))
#' gene_types(gtf)
#' # protein_coding      lncRNA     pseudogene ...
#' #         19950        16880          15200 ...
#' 
#' transcript_types(gtf)
#' }
#'
#' @name biotype-queries
#' @rdname biotype-queries
#' @export
gene_types <- function(x) {
  if (!x@available[["genes"]]) {
    stop("genes.parquet not found")
  }
  
  ds <- arrow::open_dataset(x@files$genes)
  df <- ds |> dplyr::select(gene_type) |> dplyr::collect()
  table(df$gene_type, useNA = "ifany")
}


#' @rdname biotype-queries
#' @export
transcript_types <- function(x) {
  if (!x@available[["transcripts"]]) {
    stop("transcripts.parquet not found")
  }
  
  df <- arrow::read_parquet(x@files$transcripts, col_select = "transcript_type")
  table(df$transcript_type, useNA = "ifany")
}


#' Get GTF metadata
#'
#' @description
#' Retrieve metadata from the GTF file header, including provider,
#' version, date, and genome build.
#'
#' @param x A \code{\link{GTFParquet}} object.
#'
#' @return A named character vector of metadata key-value pairs.
#'
#' @examples
#' \dontrun{
#' gtf <- GTFParquet(system.file("gc49", package="lkparq"))
#' gtf_metadata(gtf)
#' #      provider         format           date         genome 
#' #      "GENCODE"          "gtf"   "2025-07-08"       "GRCh38"
#' }
#'
#' @export
gtf_metadata <- function(x) {
  if (!x@available[["metadata"]]) {
    return(character(0))
  }
  
  meta <- arrow::read_parquet(x@files$metadata)
  setNames(meta$value, meta$name)
}


# =============================================================================
# Region Queries
# =============================================================================

#' Find features overlapping a genomic region
#'
#' @description
#' Efficient region queries that use chromosome-based filtering
#' before computing overlaps.
#'
#' @param x A \code{\link{GTFParquet}} object.
#' @param region A \link[GenomicRanges]{GRanges} object specifying the query region(s).
#' @param ... Additional arguments passed to \code{genes()} or \code{transcripts()}.
#'
#' @return A \link[GenomicRanges]{GRanges} object containing features that
#'   overlap the query region.
#'
#' @details
#' These functions first filter by chromosome (using Parquet predicate pushdown
#' for efficiency), then compute overlaps using \code{findOverlaps}.
#'
#' @examples
#' \dontrun{
#' gtf <- GTFParquet(system.file("gc49", package="lkparq"))
#' 
#' # Define a query region
#' region <- GRanges("chr1", IRanges(1000000, 2000000))
#' 
#' # Find overlapping genes
#' genes_in_region(gtf, region)
#' 
#' # Find overlapping transcripts (protein-coding only)
#' transcripts_in_region(gtf, region, 
#'                       filter = list(transcript_type = "protein_coding"))
#' }
#'
#' @name region-queries
#' @rdname region-queries
#' @export
genes_in_region <- function(x, region, ...) {
  stopifnot(inherits(region, "GRanges"))
  
  chroms <- as.character(unique(seqnames(region)))
  all_genes <- genes(x, filter = list(chrom = chroms), ...)
  
  hits <- findOverlaps(all_genes, region)
  all_genes[queryHits(hits)]
}


#' @rdname region-queries
#' @export
transcripts_in_region <- function(x, region, ...) {
  stopifnot(inherits(region, "GRanges"))
  
  chroms <- as.character(unique(seqnames(region)))
  all_tx <- transcripts(x, filter = list(chrom = chroms), ...)
  
  hits <- findOverlaps(all_tx, region)
  all_tx[queryHits(hits)]
}


# =============================================================================
# Internal Helper Functions
# =============================================================================

#' Convert data frame to GRanges with rich metadata
#' @keywords internal
.df_to_granges_rich <- function(df, id_col, mcol_cols, genome = NA_character_) {
  if (nrow(df) == 0) {
    return(GRanges())
  }
  
  gr <- GRanges(
    seqnames = df$chrom,
    ranges = IRanges(start = df$start, end = df$end),
    strand = df$strand
  )
  
  names(gr) <- df[[id_col]]
  
  exclude_cols <- c(id_col, "chrom", "start", "end", "strand")
  mcol_cols_available <- intersect(mcol_cols, colnames(df))
  mcol_cols_available <- setdiff(mcol_cols_available, exclude_cols)
  
  if (length(mcol_cols_available) > 0) {
    mcols(gr) <- df[, mcol_cols_available, drop = FALSE]
  }
  
  if (!is.na(genome)) {
    si <- seqinfo(gr)
    genome(si) <- genome
    seqinfo(gr) <- si
  }
  
  gr
}


#' Build GRangesList efficiently from pre-sorted data frame
#' @keywords internal
.df_to_grangeslist <- function(df, group_col, id_col, mcol_cols = NULL, 
                                genome = NA_character_) {
  if (nrow(df) == 0) {
    return(GRangesList())
  }
  
  groups <- df[[group_col]]
  
  gr <- GRanges(
    seqnames = df$chrom,
    ranges = IRanges(start = df$start, end = df$end),
    strand = df$strand
  )
  
  if (id_col %in% colnames(df)) {
    names(gr) <- df[[id_col]]
  }
  
  exclude_cols <- c(group_col, id_col, "chrom", "start", "end", "strand")
  mcol_cols_available <- intersect(mcol_cols, colnames(df))
  mcol_cols_available <- setdiff(mcol_cols_available, exclude_cols)
  
  if (length(mcol_cols_available) > 0) {
    mcols(gr) <- df[, mcol_cols_available, drop = FALSE]
  }
  
  if (!is.na(genome)) {
    si <- seqinfo(gr)
    genome(si) <- genome
    seqinfo(gr) <- si
  }
  
  group_factor <- factor(groups, levels = unique(groups))
  grl <- S4Vectors::splitAsList(gr, group_factor)
  
  grl
}

